/*
 * Generated by STIR. Do not edit by hand.
 */

#include <sifteo/asset.h>

#pragma once

extern Sifteo::AssetGroup IconAssets;
extern const Sifteo::AssetImage Icon;
extern Sifteo::AssetGroup GameAssets;
extern const Sifteo::PinnedAssetImage Font;
extern const Sifteo::AssetImage StationWalls;
extern const Sifteo::PinnedAssetImage Spaceman;
extern const Sifteo::AssetTracker Music;
