/*
 * Generated by STIR. Do not edit by hand.
 */

#include <sifteo/asset.h>

#pragma once

extern Sifteo::AssetGroup IconAssets;
extern const Sifteo::AssetImage Icon;
extern Sifteo::AssetGroup GameAssets;
extern const Sifteo::PinnedAssetImage Font;
extern const Sifteo::AssetImage Background;
extern const Sifteo::PinnedAssetImage Character;
extern const Sifteo::PinnedAssetImage EnemyHit;
extern const Sifteo::PinnedAssetImage CharacterWalk;
extern const Sifteo::PinnedAssetImage CharacterPunch;
extern const Sifteo::PinnedAssetImage CharacterIdle;
extern const Sifteo::PinnedAssetImage EnemyIdle;
extern const Sifteo::PinnedAssetImage Hit;
extern const Sifteo::AssetImage Fight;
extern const Sifteo::AssetImage Win;
extern const Sifteo::AssetImage WinClear;
extern const Sifteo::AssetTracker Music;
